[package]
name = "special-curves"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
num-rational = { workspace = true }
